#- "cpu_usage5,region=beijing,host=server1 core=11,usage=1100"
#- "cpu_usage5,region=beijing,host=server1 core=11,usage=1122"
#- "cpu_usage5,region=beijing,host=server1 core=11,usage=1133"
#- "cpu_usage5,region=beijing,host=server1 core=11,usage=1144"
#- "cpu_usage5,region=beijing,host=server1 core=11,usage=1155"
- "cpu_usage_func11,AGPOINTNAME=Simu1_1 wendu=666.1234,status=8208"
- "cpu_usage_func11,AGPOINTNAME=Simu1_1 wendu=555.1234,status=8208"
- "cpu_usage_func11,AGPOINTNAME=Simu1_1 wendu=444.1234,status=8208"
- "cpu_usage_func11,AGPOINTNAME=Simu1_1 wendu=333.1234,status=8208"
- "cpu_usage_func11,AGPOINTNAME=Simu1_1 wendu=222.1234,status=8208"